# Generated by Django 3.2.9 on 2021-11-09 20:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_alter_venta_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Ejemplo: 09/11/2021 17:20:00'),
        ),
    ]
