# Generated by Django 3.2.9 on 2021-11-11 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_alter_venta_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='forma_pago',
            field=models.CharField(choices=[('C', 'Contado'), ('QR', 'Código QR'), ('T', 'Tarjeta')], max_length=2),
        ),
    ]
