# Generated by Django 3.2.9 on 2021-11-11 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_alter_venta_forma_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='forma_pago',
            field=models.CharField(choices=[('Contado', 'Contado'), ('Código QR', 'Código QR'), ('Tarjeta', 'Tarjeta')], max_length=10),
        ),
    ]
