# Generated by Django 3.2.9 on 2021-11-11 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0009_formapago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='forma_pago',
            field=models.ForeignKey(help_text='Contado 10% Descuento', max_length=10, on_delete=django.db.models.deletion.CASCADE, to='ventas.formapago'),
        ),
    ]
