# Generated by Django 3.2.9 on 2021-11-03 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kindofproduct',
            options={'verbose_name': 'Tipo de producto', 'verbose_name_plural': 'Tipos de productos'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterField(
            model_name='kindofproduct',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
    ]
