# Generated by Django 3.2.9 on 2021-11-03 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_auto_20211102_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cantidad',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='precio',
            field=models.FloatField(),
        ),
    ]
