# Generated by Django 3.2.9 on 2021-11-20 21:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_auto_20211104_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cantidad',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
