# Generated by Django 3.2.9 on 2021-11-11 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_auto_20211104_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='tipo_documento',
            field=models.CharField(choices=[('DNI', 'DNI'), ('CUIL/CUIT', 'CUIL/CUIT'), ('PASAPORTE', 'PASAPORTE')], max_length=10),
        ),
    ]
