# Generated by Django 3.2.9 on 2021-11-21 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_cliente_puntos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(max_length=25, verbose_name='Teléfono'),
        ),
    ]
